// flow-typed signature: 94fab1ae299d0a0c9d1cbc11c65b6fa8
// flow-typed version: <<STUB>>/acorn-jsx_v4.0.0/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'acorn-jsx'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'acorn-jsx' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'acorn-jsx/inject' {
  declare module.exports: any;
}

declare module 'acorn-jsx/xhtml' {
  declare module.exports: any;
}

// Filename aliases
declare module 'acorn-jsx/index' {
  declare module.exports: $Exports<'acorn-jsx'>;
}
declare module 'acorn-jsx/index.js' {
  declare module.exports: $Exports<'acorn-jsx'>;
}
declare module 'acorn-jsx/inject.js' {
  declare module.exports: $Exports<'acorn-jsx/inject'>;
}
declare module 'acorn-jsx/xhtml.js' {
  declare module.exports: $Exports<'acorn-jsx/xhtml'>;
}
