// flow-typed signature: 21103da4226c7670750db0a3440c5afa
// flow-typed version: <<STUB>>/babel-preset-latest-minimal_v1.1.2/flow_v0.41.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-preset-latest-minimal'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-preset-latest-minimal' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-preset-latest-minimal/bin/list-required' {
  declare module.exports: any;
}

declare module 'babel-preset-latest-minimal/lib/index' {
  declare module.exports: any;
}

declare module 'babel-preset-latest-minimal/lib/presets/es2015' {
  declare module.exports: any;
}

declare module 'babel-preset-latest-minimal/lib/presets/es2016' {
  declare module.exports: any;
}

declare module 'babel-preset-latest-minimal/lib/presets/es2017' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-preset-latest-minimal/bin/list-required.js' {
  declare module.exports: $Exports<'babel-preset-latest-minimal/bin/list-required'>;
}
declare module 'babel-preset-latest-minimal/index' {
  declare module.exports: $Exports<'babel-preset-latest-minimal'>;
}
declare module 'babel-preset-latest-minimal/index.js' {
  declare module.exports: $Exports<'babel-preset-latest-minimal'>;
}
declare module 'babel-preset-latest-minimal/lib/index.js' {
  declare module.exports: $Exports<'babel-preset-latest-minimal/lib/index'>;
}
declare module 'babel-preset-latest-minimal/lib/presets/es2015.js' {
  declare module.exports: $Exports<'babel-preset-latest-minimal/lib/presets/es2015'>;
}
declare module 'babel-preset-latest-minimal/lib/presets/es2016.js' {
  declare module.exports: $Exports<'babel-preset-latest-minimal/lib/presets/es2016'>;
}
declare module 'babel-preset-latest-minimal/lib/presets/es2017.js' {
  declare module.exports: $Exports<'babel-preset-latest-minimal/lib/presets/es2017'>;
}
