// flow-typed signature: d17ce4dbe9506b3e5968f8461d7bbc7c
// flow-typed version: <<STUB>>/client-oauth2_v3.4.1/flow_v0.40.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'client-oauth2'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'client-oauth2' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'client-oauth2/src/client-oauth2' {
  declare module.exports: any;
}

declare module 'client-oauth2/src/request/browser' {
  declare module.exports: any;
}

declare module 'client-oauth2/src/request/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'client-oauth2/src/client-oauth2.js' {
  declare module.exports: $Exports<'client-oauth2/src/client-oauth2'>;
}
declare module 'client-oauth2/src/request/browser.js' {
  declare module.exports: $Exports<'client-oauth2/src/request/browser'>;
}
declare module 'client-oauth2/src/request/index.js' {
  declare module.exports: $Exports<'client-oauth2/src/request/index'>;
}
