// flow-typed signature: c9c7ac231893aaec79ee39b13d9ee709
// flow-typed version: <<STUB>>/koa-compose_v3.2.1/flow_v0.41.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'koa-compose'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'koa-compose' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'koa-compose/index' {
  declare module.exports: $Exports<'koa-compose'>;
}
declare module 'koa-compose/index.js' {
  declare module.exports: $Exports<'koa-compose'>;
}
