// flow-typed signature: 2e44a9062e14a1ef3e613f0334240fcd
// flow-typed version: <<STUB>>/koa-morgan_v1.0.1/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'koa-morgan'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'koa-morgan' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'koa-morgan/index' {
  declare module.exports: $Exports<'koa-morgan'>;
}
declare module 'koa-morgan/index.js' {
  declare module.exports: $Exports<'koa-morgan'>;
}
