// flow-typed signature: a9797296dbf08edcd47f5e44e4c9381b
// flow-typed version: <<STUB>>/lerna-semantic-release_v9.0.7/flow_v0.41.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lerna-semantic-release'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'lerna-semantic-release' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'lerna-semantic-release/bin/lerna-semantic-release' {
  declare module.exports: any;
}

// Filename aliases
declare module 'lerna-semantic-release/bin/lerna-semantic-release.js' {
  declare module.exports: $Exports<'lerna-semantic-release/bin/lerna-semantic-release'>;
}
