// flow-typed signature: 44a04c1e18017532ae81495574e10362
// flow-typed version: <<STUB>>/mosaic-component-example_v1.0.2/flow_v0.39.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mosaic-component-example'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'mosaic-component-example' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mosaic-component-example/dist/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mosaic-component-example/dist/index.js' {
  declare module.exports: $Exports<'mosaic-component-example/dist/index'>;
}
