// flow-typed signature: 5a6c7f522ff312a6f3f9f2fa9da12471
// flow-typed version: <<STUB>>/node-tokens_v0.0.9/flow_v0.39.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'node-tokens'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'node-tokens' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'node-tokens/src/default' {
  declare module.exports: any;
}

declare module 'node-tokens/src/local' {
  declare module.exports: any;
}

declare module 'node-tokens/test/default.test' {
  declare module.exports: any;
}

declare module 'node-tokens/test/index.test' {
  declare module.exports: any;
}

declare module 'node-tokens/test/local.test' {
  declare module.exports: any;
}

declare module 'node-tokens/test/mocha-globals' {
  declare module.exports: any;
}

// Filename aliases
declare module 'node-tokens/index' {
  declare module.exports: $Exports<'node-tokens'>;
}
declare module 'node-tokens/index.js' {
  declare module.exports: $Exports<'node-tokens'>;
}
declare module 'node-tokens/src/default.js' {
  declare module.exports: $Exports<'node-tokens/src/default'>;
}
declare module 'node-tokens/src/local.js' {
  declare module.exports: $Exports<'node-tokens/src/local'>;
}
declare module 'node-tokens/test/default.test.js' {
  declare module.exports: $Exports<'node-tokens/test/default.test'>;
}
declare module 'node-tokens/test/index.test.js' {
  declare module.exports: $Exports<'node-tokens/test/index.test'>;
}
declare module 'node-tokens/test/local.test.js' {
  declare module.exports: $Exports<'node-tokens/test/local.test'>;
}
declare module 'node-tokens/test/mocha-globals.js' {
  declare module.exports: $Exports<'node-tokens/test/mocha-globals'>;
}
