// flow-typed signature: 510827febb6cee4313f613148fa24644
// flow-typed version: <<STUB>>/prometheus-gc-stats_v0.3.4/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'prometheus-gc-stats'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'prometheus-gc-stats' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'prometheus-gc-stats/index' {
  declare module.exports: $Exports<'prometheus-gc-stats'>;
}
declare module 'prometheus-gc-stats/index.js' {
  declare module.exports: $Exports<'prometheus-gc-stats'>;
}
