// flow-typed signature: cd2da98cbe79d2b523930a69ce054cff
// flow-typed version: <<STUB>>/prom-client_v7.1.0/flow_v0.40.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'prom-client'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'prom-client' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'prom-client/lib/bucketGenerators' {
  declare module.exports: any;
}

declare module 'prom-client/lib/counter' {
  declare module.exports: any;
}

declare module 'prom-client/lib/defaultMetrics' {
  declare module.exports: any;
}

declare module 'prom-client/lib/gauge' {
  declare module.exports: any;
}

declare module 'prom-client/lib/histogram' {
  declare module.exports: any;
}

declare module 'prom-client/lib/metrics/eventLoopLag' {
  declare module.exports: any;
}

declare module 'prom-client/lib/metrics/heapSizeAndUsed' {
  declare module.exports: any;
}

declare module 'prom-client/lib/metrics/heapSpacesSizeAndUsed' {
  declare module.exports: any;
}

declare module 'prom-client/lib/metrics/osMemoryHeap' {
  declare module.exports: any;
}

declare module 'prom-client/lib/metrics/osMemoryHeapLinux' {
  declare module.exports: any;
}

declare module 'prom-client/lib/metrics/processCpuTotal' {
  declare module.exports: any;
}

declare module 'prom-client/lib/metrics/processHandles' {
  declare module.exports: any;
}

declare module 'prom-client/lib/metrics/processMaxFileDescriptors' {
  declare module.exports: any;
}

declare module 'prom-client/lib/metrics/processOpenFileDescriptors' {
  declare module.exports: any;
}

declare module 'prom-client/lib/metrics/processRequests' {
  declare module.exports: any;
}

declare module 'prom-client/lib/metrics/processStartTime' {
  declare module.exports: any;
}

declare module 'prom-client/lib/pushgateway' {
  declare module.exports: any;
}

declare module 'prom-client/lib/register' {
  declare module.exports: any;
}

declare module 'prom-client/lib/summary' {
  declare module.exports: any;
}

declare module 'prom-client/lib/util' {
  declare module.exports: any;
}

declare module 'prom-client/lib/validation' {
  declare module.exports: any;
}

// Filename aliases
declare module 'prom-client/index' {
  declare module.exports: $Exports<'prom-client'>;
}
declare module 'prom-client/index.js' {
  declare module.exports: $Exports<'prom-client'>;
}
declare module 'prom-client/lib/bucketGenerators.js' {
  declare module.exports: $Exports<'prom-client/lib/bucketGenerators'>;
}
declare module 'prom-client/lib/counter.js' {
  declare module.exports: $Exports<'prom-client/lib/counter'>;
}
declare module 'prom-client/lib/defaultMetrics.js' {
  declare module.exports: $Exports<'prom-client/lib/defaultMetrics'>;
}
declare module 'prom-client/lib/gauge.js' {
  declare module.exports: $Exports<'prom-client/lib/gauge'>;
}
declare module 'prom-client/lib/histogram.js' {
  declare module.exports: $Exports<'prom-client/lib/histogram'>;
}
declare module 'prom-client/lib/metrics/eventLoopLag.js' {
  declare module.exports: $Exports<'prom-client/lib/metrics/eventLoopLag'>;
}
declare module 'prom-client/lib/metrics/heapSizeAndUsed.js' {
  declare module.exports: $Exports<'prom-client/lib/metrics/heapSizeAndUsed'>;
}
declare module 'prom-client/lib/metrics/heapSpacesSizeAndUsed.js' {
  declare module.exports: $Exports<'prom-client/lib/metrics/heapSpacesSizeAndUsed'>;
}
declare module 'prom-client/lib/metrics/osMemoryHeap.js' {
  declare module.exports: $Exports<'prom-client/lib/metrics/osMemoryHeap'>;
}
declare module 'prom-client/lib/metrics/osMemoryHeapLinux.js' {
  declare module.exports: $Exports<'prom-client/lib/metrics/osMemoryHeapLinux'>;
}
declare module 'prom-client/lib/metrics/processCpuTotal.js' {
  declare module.exports: $Exports<'prom-client/lib/metrics/processCpuTotal'>;
}
declare module 'prom-client/lib/metrics/processHandles.js' {
  declare module.exports: $Exports<'prom-client/lib/metrics/processHandles'>;
}
declare module 'prom-client/lib/metrics/processMaxFileDescriptors.js' {
  declare module.exports: $Exports<'prom-client/lib/metrics/processMaxFileDescriptors'>;
}
declare module 'prom-client/lib/metrics/processOpenFileDescriptors.js' {
  declare module.exports: $Exports<'prom-client/lib/metrics/processOpenFileDescriptors'>;
}
declare module 'prom-client/lib/metrics/processRequests.js' {
  declare module.exports: $Exports<'prom-client/lib/metrics/processRequests'>;
}
declare module 'prom-client/lib/metrics/processStartTime.js' {
  declare module.exports: $Exports<'prom-client/lib/metrics/processStartTime'>;
}
declare module 'prom-client/lib/pushgateway.js' {
  declare module.exports: $Exports<'prom-client/lib/pushgateway'>;
}
declare module 'prom-client/lib/register.js' {
  declare module.exports: $Exports<'prom-client/lib/register'>;
}
declare module 'prom-client/lib/summary.js' {
  declare module.exports: $Exports<'prom-client/lib/summary'>;
}
declare module 'prom-client/lib/util.js' {
  declare module.exports: $Exports<'prom-client/lib/util'>;
}
declare module 'prom-client/lib/validation.js' {
  declare module.exports: $Exports<'prom-client/lib/validation'>;
}
