// flow-typed signature: 76bf7ece2e90e6b87f9c071ea1d60dae
// flow-typed version: <<STUB>>/prometheus-gc-stats_v0.3.2/flow_v0.39.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'prometheus-gc-stats'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'prometheus-gc-stats' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'prometheus-gc-stats/index' {
  declare module.exports: $Exports<'prometheus-gc-stats'>;
}
declare module 'prometheus-gc-stats/index.js' {
  declare module.exports: $Exports<'prometheus-gc-stats'>;
}
