// flow-typed signature: 74aab79686ccb3fedb47e4fb21843068
// flow-typed version: <<STUB>>/request-promise-native_v1.0.3/flow_v0.41.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'request-promise-native'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'request-promise-native' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'request-promise-native/errors' {
  declare module.exports: any;
}

declare module 'request-promise-native/lib/rp' {
  declare module.exports: any;
}

// Filename aliases
declare module 'request-promise-native/errors.js' {
  declare module.exports: $Exports<'request-promise-native/errors'>;
}
declare module 'request-promise-native/lib/rp.js' {
  declare module.exports: $Exports<'request-promise-native/lib/rp'>;
}
