// flow-typed signature: 3b4533f88b8a750acf79d9645528a725
// flow-typed version: <<STUB>>/tessellate-server_v1.1.0/flow_v0.41.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'tessellate-server'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'tessellate-server' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'tessellate-server/dist/error' {
  declare module.exports: any;
}

declare module 'tessellate-server/dist/index' {
  declare module.exports: any;
}

declare module 'tessellate-server/dist/MetricsApp' {
  declare module.exports: any;
}

declare module 'tessellate-server/dist/nconf' {
  declare module.exports: any;
}

declare module 'tessellate-server/dist/TessellateServer' {
  declare module.exports: any;
}

declare module 'tessellate-server/example/server' {
  declare module.exports: any;
}

declare module 'tessellate-server/src/error' {
  declare module.exports: any;
}

declare module 'tessellate-server/src/index' {
  declare module.exports: any;
}

declare module 'tessellate-server/src/MetricsApp' {
  declare module.exports: any;
}

declare module 'tessellate-server/src/nconf' {
  declare module.exports: any;
}

declare module 'tessellate-server/src/TessellateServer' {
  declare module.exports: any;
}

declare module 'tessellate-server/test/nconf.test' {
  declare module.exports: any;
}

declare module 'tessellate-server/test/TessellateServer.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'tessellate-server/dist/error.js' {
  declare module.exports: $Exports<'tessellate-server/dist/error'>;
}
declare module 'tessellate-server/dist/index.js' {
  declare module.exports: $Exports<'tessellate-server/dist/index'>;
}
declare module 'tessellate-server/dist/MetricsApp.js' {
  declare module.exports: $Exports<'tessellate-server/dist/MetricsApp'>;
}
declare module 'tessellate-server/dist/nconf.js' {
  declare module.exports: $Exports<'tessellate-server/dist/nconf'>;
}
declare module 'tessellate-server/dist/TessellateServer.js' {
  declare module.exports: $Exports<'tessellate-server/dist/TessellateServer'>;
}
declare module 'tessellate-server/example/server.js' {
  declare module.exports: $Exports<'tessellate-server/example/server'>;
}
declare module 'tessellate-server/src/error.js' {
  declare module.exports: $Exports<'tessellate-server/src/error'>;
}
declare module 'tessellate-server/src/index.js' {
  declare module.exports: $Exports<'tessellate-server/src/index'>;
}
declare module 'tessellate-server/src/MetricsApp.js' {
  declare module.exports: $Exports<'tessellate-server/src/MetricsApp'>;
}
declare module 'tessellate-server/src/nconf.js' {
  declare module.exports: $Exports<'tessellate-server/src/nconf'>;
}
declare module 'tessellate-server/src/TessellateServer.js' {
  declare module.exports: $Exports<'tessellate-server/src/TessellateServer'>;
}
declare module 'tessellate-server/test/nconf.test.js' {
  declare module.exports: $Exports<'tessellate-server/test/nconf.test'>;
}
declare module 'tessellate-server/test/TessellateServer.test.js' {
  declare module.exports: $Exports<'tessellate-server/test/TessellateServer.test'>;
}
