// flow-typed signature: d3e5c8c0f45e9ac51805a4389b1568df
// flow-typed version: <<STUB>>/tessellate-request_v1.1.0/flow_v0.41.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'tessellate-request'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'tessellate-request' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'tessellate-request/dist/index' {
  declare module.exports: any;
}

declare module 'tessellate-request/flow/auth-configuration' {
  declare module.exports: any;
}

declare module 'tessellate-request/lib/configurations/configuration-loader-factory' {
  declare module.exports: any;
}

declare module 'tessellate-request/lib/configurations/configuration-loader' {
  declare module.exports: any;
}

declare module 'tessellate-request/lib/configurations/configuration-provider' {
  declare module.exports: any;
}

declare module 'tessellate-request/lib/configurations/configuration-type' {
  declare module.exports: any;
}

declare module 'tessellate-request/lib/configurations/file-configuration-loader' {
  declare module.exports: any;
}

declare module 'tessellate-request/lib/configurations/token-storage' {
  declare module.exports: any;
}

declare module 'tessellate-request/lib/index' {
  declare module.exports: any;
}

declare module 'tessellate-request/lib/requests/default-request' {
  declare module.exports: any;
}

declare module 'tessellate-request/lib/requests/file-backed-oauth-request' {
  declare module.exports: any;
}

declare module 'tessellate-request/lib/requests/request-factory' {
  declare module.exports: any;
}

declare module 'tessellate-request/lib/requests/smart-request' {
  declare module.exports: any;
}

// Filename aliases
declare module 'tessellate-request/dist/index.js' {
  declare module.exports: $Exports<'tessellate-request/dist/index'>;
}
declare module 'tessellate-request/flow/auth-configuration.js' {
  declare module.exports: $Exports<'tessellate-request/flow/auth-configuration'>;
}
declare module 'tessellate-request/lib/configurations/configuration-loader-factory.js' {
  declare module.exports: $Exports<'tessellate-request/lib/configurations/configuration-loader-factory'>;
}
declare module 'tessellate-request/lib/configurations/configuration-loader.js' {
  declare module.exports: $Exports<'tessellate-request/lib/configurations/configuration-loader'>;
}
declare module 'tessellate-request/lib/configurations/configuration-provider.js' {
  declare module.exports: $Exports<'tessellate-request/lib/configurations/configuration-provider'>;
}
declare module 'tessellate-request/lib/configurations/configuration-type.js' {
  declare module.exports: $Exports<'tessellate-request/lib/configurations/configuration-type'>;
}
declare module 'tessellate-request/lib/configurations/file-configuration-loader.js' {
  declare module.exports: $Exports<'tessellate-request/lib/configurations/file-configuration-loader'>;
}
declare module 'tessellate-request/lib/configurations/token-storage.js' {
  declare module.exports: $Exports<'tessellate-request/lib/configurations/token-storage'>;
}
declare module 'tessellate-request/lib/index.js' {
  declare module.exports: $Exports<'tessellate-request/lib/index'>;
}
declare module 'tessellate-request/lib/requests/default-request.js' {
  declare module.exports: $Exports<'tessellate-request/lib/requests/default-request'>;
}
declare module 'tessellate-request/lib/requests/file-backed-oauth-request.js' {
  declare module.exports: $Exports<'tessellate-request/lib/requests/file-backed-oauth-request'>;
}
declare module 'tessellate-request/lib/requests/request-factory.js' {
  declare module.exports: $Exports<'tessellate-request/lib/requests/request-factory'>;
}
declare module 'tessellate-request/lib/requests/smart-request.js' {
  declare module.exports: $Exports<'tessellate-request/lib/requests/smart-request'>;
}
