// flow-typed signature: 8a33a219fae1a94bb9b42d1c09086976
// flow-typed version: <<STUB>>/tessellate-render_v0.1.0/flow_v0.39.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'tessellate-render'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'tessellate-render' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'tessellate-render/coverage/lcov-report/prettify' {
  declare module.exports: any;
}

declare module 'tessellate-render/coverage/lcov-report/sorter' {
  declare module.exports: any;
}

declare module 'tessellate-render/coverage/prettify' {
  declare module.exports: any;
}

declare module 'tessellate-render/coverage/sorter' {
  declare module.exports: any;
}

declare module 'tessellate-render/dist/index' {
  declare module.exports: any;
}

declare module 'tessellate-render/dist/SandboxVM' {
  declare module.exports: any;
}

declare module 'tessellate-render/lib/index' {
  declare module.exports: any;
}

declare module 'tessellate-render/lib/SandboxVM' {
  declare module.exports: any;
}

declare module 'tessellate-render/test/index.test' {
  declare module.exports: any;
}

declare module 'tessellate-render/test/SandboxVM.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'tessellate-render/coverage/lcov-report/prettify.js' {
  declare module.exports: $Exports<'tessellate-render/coverage/lcov-report/prettify'>;
}
declare module 'tessellate-render/coverage/lcov-report/sorter.js' {
  declare module.exports: $Exports<'tessellate-render/coverage/lcov-report/sorter'>;
}
declare module 'tessellate-render/coverage/prettify.js' {
  declare module.exports: $Exports<'tessellate-render/coverage/prettify'>;
}
declare module 'tessellate-render/coverage/sorter.js' {
  declare module.exports: $Exports<'tessellate-render/coverage/sorter'>;
}
declare module 'tessellate-render/dist/index.js' {
  declare module.exports: $Exports<'tessellate-render/dist/index'>;
}
declare module 'tessellate-render/dist/SandboxVM.js' {
  declare module.exports: $Exports<'tessellate-render/dist/SandboxVM'>;
}
declare module 'tessellate-render/lib/index.js' {
  declare module.exports: $Exports<'tessellate-render/lib/index'>;
}
declare module 'tessellate-render/lib/SandboxVM.js' {
  declare module.exports: $Exports<'tessellate-render/lib/SandboxVM'>;
}
declare module 'tessellate-render/test/index.test.js' {
  declare module.exports: $Exports<'tessellate-render/test/index.test'>;
}
declare module 'tessellate-render/test/SandboxVM.test.js' {
  declare module.exports: $Exports<'tessellate-render/test/SandboxVM.test'>;
}
