// flow-typed signature: fa6cabbb3fc7fecefcefd1f8bf0bbf82
// flow-typed version: <<STUB>>/thenify_v3.2.1/flow_v0.40.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'thenify'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'thenify' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'thenify/index' {
  declare module.exports: $Exports<'thenify'>;
}
declare module 'thenify/index.js' {
  declare module.exports: $Exports<'thenify'>;
}
